### ISSUE TITLE
Ed25519 keys are not fully supported.

### ISSUE THREAD

**Issue by brendoncarroll** [pion/dtls#469] opened 2022-05-20 21:02 UTC
I first noticed this issue trying to self sign a certificate with an Ed25519 key.  Ed25519 keys do not work for self-signing client certificates.

On the client:
```
handshake error: alert: Alert Fatal: BadCertificate
```

On the server:
```
handshake error: dtls fatal: expected and actual key signature do not match
```

But that is just the proximate problem I am having.  Several tests fail if you apply this diff, which switches to ed25519 keys in the `selfsigned` package.

```
diff --git a/pkg/crypto/selfsign/selfsign.go b/pkg/crypto/selfsign/selfsign.go
index 581e0a2..e3b57ac 100644
--- a/pkg/crypto/selfsign/selfsign.go
+++ b/pkg/crypto/selfsign/selfsign.go
@@ -5,7 +5,6 @@ import (
        "crypto"
        "crypto/ecdsa"
        "crypto/ed25519"
-       "crypto/elliptic"
        "crypto/rand"
        "crypto/rsa"
        "crypto/tls"
@@ -20,17 +19,16 @@ var errInvalidPrivateKey = errors.New("selfsign: invalid private key type")

 // GenerateSelfSigned creates a self-signed certificate
 func GenerateSelfSigned() (tls.Certificate, error) {
-       priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
+       _, priv, err := ed25519.GenerateKey(rand.Reader)
        if err != nil {
                return tls.Certificate{}, err
        }
-
        return SelfSign(priv)
 }

 // GenerateSelfSignedWithDNS creates a self-signed certificate
 func GenerateSelfSignedWithDNS(cn string, sans ...string) (tls.Certificate, error) {
-       priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
+       _, priv, err := ed25519.GenerateKey(rand.Reader)
        if err != nil {
                return tls.Certificate{}, err
        }
```

Failing tests:
```
--- FAIL: TestHandshakeWithAlert (0.41s)
    --- FAIL: TestHandshakeWithAlert/SignatureSchemesNoIntersection (0.00s)
--- FAIL: TestClientCertificate (0.42s)
    --- FAIL: TestClientCertificate/parallel (0.01s)
        --- FAIL: TestClientCertificate/parallel/NoClientCert_cert (0.00s)
        --- FAIL: TestClientCertificate/parallel/RequireAnyClientCert (0.00s)
        --- FAIL: TestClientCertificate/parallel/VerifyClientCertIfGiven_cert (0.00s)
        --- FAIL: TestClientCertificate/parallel/RequireAndVerifyClientCert (0.00s)
        --- FAIL: TestClientCertificate/parallel/RequestClientCert_cert (0.00s)
--- FAIL: TestServerCertificate (0.43s)
    --- FAIL: TestServerCertificate/parallel (0.02s)
        --- FAIL: TestServerCertificate/parallel/good_ca_skip_verify_custom_verify_peer (0.00s)
        --- FAIL: TestServerCertificate/parallel/good_ca_verify_custom_verify_peer (0.00s)
--- FAIL: TestErrorsTemporary (0.00s)
```

**Comment by daenney** [comment] 2022-05-21 12:29
I suspect the problem is elsewhere. We have E2E tests with self-signed ED25519 certs generated by us https://github.com/pion/dtls/blob/84b65ad6309d39a1f01204667d1cecbf9e016341/e2e/e2e_test.go#L325-L363

We also have Pion as a server with OpenSSL as a client https://github.com/pion/dtls/blob/84b65ad6309d39a1f01204667d1cecbf9e016341/e2e/e2e_openssl_test.go#L294-L304

Both set of tests pass and generate the key the same way as your changeset:
```go
_, key, err := ed25519.GenerateKey(rand.Reader)
if err != nil {
	t.Fatal(err)
}
cert, err := selfsign.SelfSign(key)
if err != nil {
	t.Fatal(err)
}
```

**Comment by daenney** [comment] 2022-05-21 12:35
The tests break for a number of reasons:

` TestHandshakeWithAlert/SignatureSchemesNoIntersection` explicitly tests with ECDSA keys, and a signature scheme that only supports those. You've changed it to generate ED25519 keys, but have not adapted the test accordingly:
```
"SignatureSchemesNoIntersection": {
			configServer: &Config{
				CipherSuites:     []CipherSuiteID{TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256},
				SignatureSchemes: []tls.SignatureScheme{tls.ECDSAWithP256AndSHA256},
			},
			configClient: &Config{
				CipherSuites:     []CipherSuiteID{TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256},
				SignatureSchemes: []tls.SignatureScheme{tls.ECDSAWithP521AndSHA512},
			},
```

We explicitly expect `tls.ECDSAWithP521AndSHA512` which is not the case when using ED25519 keys. I suspect the rest of the tests fail for much the same reason. `GenerateSelfSigned` has always returned ECDSA keys. Changing the implementation of it to return an ED25519 key, without adjusting the tests accordingly will indeed cause the tests to fail.

**Comment by daenney** [comment] 2022-05-22 13:02
Sorry, didn't mean to actually close this. I just dug a little deeper and you're right, it fails with a client cert, which our E2E tests aren't catching.

**Comment by daenney** [comment] 2022-05-22 13:44
@Sean-Der I'm honestly a little mystified here. My suspicion is that we're doing something wrong in `selfsign.WithDNS` since that's where we end up: https://github.com/pion/dtls/blob/84b65ad6309d39a1f01204667d1cecbf9e016341/pkg/crypto/selfsign/selfsign.go#L47-L100

But we appear to be matching https://go.dev/src/crypto/tls/generate_cert.go so I suspect that's fine.

I patched our examples to use ed25519 keys in the way I would expect them to work, and we do indeed get a handshake failure when you run them with this:

```diff
diff --git a/examples/dial/selfsign/main.go b/examples/dial/selfsign/main.go
index 7ff2926..8820856 100644
--- a/examples/dial/selfsign/main.go
+++ b/examples/dial/selfsign/main.go
@@ -2,6 +2,8 @@ package main
 
 import (
 	"context"
+	"crypto/ed25519"
+	"crypto/rand"
 	"crypto/tls"
 	"fmt"
 	"net"
@@ -17,8 +19,11 @@ func main() {
 	addr := &net.UDPAddr{IP: net.ParseIP("127.0.0.1"), Port: 4444}
 
 	// Generate a certificate and private key to secure the connection
-	certificate, genErr := selfsign.GenerateSelfSigned()
-	util.Check(genErr)
+	_, priv, err := ed25519.GenerateKey(rand.Reader)
+	util.Check(err)
+	ss, err := selfsign.SelfSign(priv)
+
+	util.Check(err)
 
 	//
 	// Everything below is the pion-DTLS API! Thanks for using it ❤️.
@@ -26,7 +31,14 @@ func main() {
 
 	// Prepare the configuration of the DTLS connection
 	config := &dtls.Config{
-		Certificates:         []tls.Certificate{certificate},
+		Certificates: []tls.Certificate{ss},
+		CipherSuites: []dtls.CipherSuiteID{
+			dtls.TLS_ECDHE_ECDSA_WITH_AES_128_CCM,
+			dtls.TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8,
+			dtls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
+			dtls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
+			dtls.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
+		},
 		InsecureSkipVerify:   true,
 		ExtendedMasterSecret: dtls.RequireExtendedMasterSecret,
 	}
diff --git a/examples/listen/selfsign/main.go b/examples/listen/selfsign/main.go
index 2df4ac4..4a0b8a4 100644
--- a/examples/listen/selfsign/main.go
+++ b/examples/listen/selfsign/main.go
@@ -2,6 +2,8 @@ package main
 
 import (
 	"context"
+	"crypto/ed25519"
+	"crypto/rand"
 	"crypto/tls"
 	"fmt"
 	"net"
@@ -17,8 +19,11 @@ func main() {
 	addr := &net.UDPAddr{IP: net.ParseIP("127.0.0.1"), Port: 4444}
 
 	// Generate a certificate and private key to secure the connection
-	certificate, genErr := selfsign.GenerateSelfSigned()
-	util.Check(genErr)
+	_, priv, err := ed25519.GenerateKey(rand.Reader)
+	util.Check(err)
+	ss, err := selfsign.SelfSign(priv)
+
+	util.Check(err)
 
 	// Create parent context to cleanup handshaking connections on exit.
 	ctx, cancel := context.WithCancel(context.Background())
@@ -30,9 +35,17 @@ func main() {
 
 	// Prepare the configuration of the DTLS connection
 	config := &dtls.Config{
-		Certificates:         []tls.Certificate{certificate},
+		Certificates: []tls.Certificate{ss},
+		CipherSuites: []dtls.CipherSuiteID{
+			dtls.TLS_ECDHE_ECDSA_WITH_AES_128_CCM,
+			dtls.TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8,
+			dtls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
+			dtls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
+			dtls.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
+		},
 		ExtendedMasterSecret: dtls.RequireExtendedMasterSecret,
 		// Create timeout context for accepted connection.
+		ClientAuth: dtls.RequestClientCert,
 		ConnectContextMaker: func() (context.Context, func()) {
 			return context.WithTimeout(ctx, 30*time.Second)
 		},
```

**Comment by daenney** [comment] 2022-05-22 13:54
Uhg, I think I found it: https://github.com/pion/dtls/blob/84b65ad6309d39a1f01204667d1cecbf9e016341/crypto.go#L110-L128

Notice the comment on `case ed25519.PrivateKey`? We're not supposed to hash ourselves, yet we pass in `hashed`, not `handshakeBodies`. Changing that to `handshakeBodies` now makes the examples work.

We're generating the CertificateVerify incorrectly in the case of ed25519.

**Comment by daenney** [comment] 2022-05-22 14:08
@brendoncarroll Mind trying out #470 and see if that works for you now?

**Closed** 2022-05-24 08:20 UTC
