### ISSUE TITLE
Closing connection on the server causes fatal error from Accept()

### ISSUE THREAD

**Issue by folbricht** [pion/dtls#255] opened 2020-05-26 15:13 UTC
### Your environment.
  - Version: v2.0.0
  - Browser: n/a
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?

- Start a server with an Accept() loop
- Have a client connect to the server and just Read() on the connection
- The server actively closes the connection

Server:
```go
package main

import (
	"context"
	"fmt"
	"net"
	"time"

	"github.com/pion/dtls/v2"
	"github.com/pion/dtls/v2/examples/util"
)

func main() {
	addr := &net.UDPAddr{IP: net.ParseIP("127.0.0.1"), Port: 4444}

	config := &dtls.Config{
		PSK: func(hint []byte) ([]byte, error) {
			return []byte{0xAB, 0xC1, 0x23}, nil
		},
		PSKIdentityHint:      []byte("Pion DTLS Client"),
		CipherSuites:         []dtls.CipherSuiteID{dtls.TLS_PSK_WITH_AES_128_CCM_8},
		ExtendedMasterSecret: dtls.RequireExtendedMasterSecret,
		ConnectContextMaker: func() (context.Context, func()) {
			return context.WithTimeout(context.Background(), 2*time.Second)
		},
	}

	listener, err := dtls.Listen("udp", addr, config)
	util.Check(err)

	for {
		fmt.Println("waiting for connection")
		conn, err := listener.Accept()
		if err != nil {
			if netErr, ok := err.(net.Error); ok && netErr.Temporary() {
				fmt.Println("tempoary error, continuing")
				continue
			}
			fmt.Println("permanent error")
			panic(err)
		}

		go func() {
			fmt.Println("closing connection in 1s")
			time.Sleep(time.Second)
			conn.Close()
		}()
	}
}
```

Client:
```go
package main

import (
	"fmt"
	"io"
	"net"
	"os"

	"github.com/pion/dtls/v2"
	"github.com/pion/dtls/v2/examples/util"
)

func main() {
	addr := &net.UDPAddr{IP: net.ParseIP("127.0.0.1"), Port: 4444}

	config := &dtls.Config{
		PSK: func(hint []byte) ([]byte, error) {
			return []byte{0xAB, 0xC1, 0x23}, nil
		},
		PSKIdentityHint:      []byte("Pion DTLS Server"),
		CipherSuites:         []dtls.CipherSuiteID{dtls.TLS_PSK_WITH_AES_128_CCM_8},
		ExtendedMasterSecret: dtls.RequireExtendedMasterSecret,
	}

	conn, err := dtls.Dial("udp", addr, config)
	util.Check(err)

	fmt.Println("Connected")
	io.Copy(os.Stdout, conn)
}
```

### What did you expect?

Expected the connection to be closed and the server to keep accepting future (new) connections.

### What happened?

The connection is closed, but by doing do, the server's Accept() receives a confirmation from the client which triggers a new handshake. Since this isn't a real handshake, it times out and becomes a Fatal error from listener.Accept() which usually fails the server.

If you let me know how best to address this, I can try to make a PR for it. Perhaps the response from the client shouldn't trigger another handshake, and it's probably best to not make handshake timeouts fatal errors anyway.

**Comment by at-wat** [comment] 2020-05-26 15:49
Thanks for your report.
The bug seems be caused by following sequence:
```
server: conn.Close()
server: send AlertCloseNotify
server: conn is released
        (it is legal in RFC to release the resources immediately
         without waiting client's AlertCloseNotify)
client: receive AlertCloseNotify
client: send AlertCloseNotify back
client: conn is released
server: receive AlertCloseNotify
        Since the source of the packet is not registered (already released),
        it is treated as a new connection and start handshake.
        (basic logic is under internal/net/udp)
server: handshake timeout
```
I think `dtls.Listener` should not start handshake process if the first packet, which created `internal/net/udp.Conn`, is not `ClientHello`.

> and it's probably best to not make handshake timeouts fatal errors anyway.

I agree for the case of `Accept()`. (`Accept()` internally calls `Server()`)
But for `Server(), Client(), Dial()`, handshake timeout should be fatal IMO.

**Comment by at-wat** [comment] 2020-05-26 16:01
> I think `dtls.Listener` should not start handshake process if the first packet, which created `internal/net/udp.Conn`, is not `ClientHello`.

Maybe adding a filter func, that determines whether the new conn should be made or not, to `internal.net.udp.ListenConfig struct` would be good.
https://github.com/pion/dtls/blob/52af2bfea38ea292b1f63b2067d3cb5aefd35430/internal/net/udp/conn.go#L96-L105

**Comment by folbricht** [comment] 2020-05-27 02:22
Sorry, I can't find a good way to add that in. Ideally it wouldn't even start `Server()` with this new conn. I don't see how to tell if it's a `ClientHello` that early on, without starting the handshake much later. Personally I'd probably keep the client reference for some time after `Close()` and drop further packets for a little while longer. Do you prefer your solution of adding a filter?

**Comment by at-wat** [comment] 2020-05-27 10:38
Created a PR to specify a filter func to low layer Accept.
https://github.com/pion/dtls/pull/257
I think this is better solution since if the server creates handshaker and all resources for any input packet, it decreases tolerance against DoS attack.

Making such error from `Accept()` temporary should be fixed by an another PR.

**Comment by folbricht** [comment] 2020-05-27 13:00
Thanks for that. Works as expected.

As for the error from `Accept()`, to avoid changing the FatalError that currently comes out of `Server()`, I was thinking of catching that, and re-wrapping the inner Err as a temporary error here: https://github.com/pion/dtls/blob/3028bdc24d38a2268d0d6513e0debf130d67ee4c/listener.go#L48-L52

**Closed** 2020-06-02 14:04 UTC
